#!/bin/bash
# @author : Imaginary
# @date : 2017/12/26

source /etc/profile

BASE_NAME=rest-api
APP_HOME=/usr/local/$BASE_NAME
APP_MAINCLASS="Application"
APP_JAR=$APP_HOME/lib/$BASE_NAME-1.0.jar.original



APP_NAME=$BASE_NAME-1.0
[ ! -d ${JAVA_HOME} ] && {
    echo "JAVA_HOME IS NOT CONFIGURED."
	    exit 0
}

psid=0 

checkpid() { 
	javaps=`$JAVA_HOME/bin/jps -l | grep -E "$APP_MAINCLASS|$APP_NAME"` 
	if [ -n "$javaps" ]; then 
		psid=`echo $javaps | awk '{print $1}'` 
	else 
		psid=0 
	fi 
}

start() { 
	checkpid 

	if [ $psid -ne 0 ]; then 
		echo "================================" 
		echo "warn: $APP_NAME already started! (pid=$psid)" 
		echo "================================" 
	else 
		echo -n "Starting $APP_NAME ..." 
        /usr/bin/python /usr/local/bin/initx $BASE_NAME
		nohup java -jar $APP_JAR --spring.config.location=$APP_HOME/conf/application.yml >/dev/null 2>&1 &
		checkpid
		if [ $psid -ne 0 ]; then 
			echo "(pid=$psid) [OK]" 
		else 
			echo "[Failed]" 
		fi 
	fi 
} 

stop() { 
	checkpid 

	if [ $psid -ne 0 ]; then 
		echo -n "Stopping $APP_NAME ...(pid=$psid) " 
		kill -9 $psid
		if [ $? -eq 0 ]; then 
			echo "[OK]" 
		else 
			echo "[Failed]" 
		fi 

		checkpid 
		if [ $psid -ne 0 ]; then 
			stop 
		fi 
	else 
		echo "================================" 
		echo "warn: $APP_NAME is not running" 
		echo "================================" 
	fi 
}

status() { 
	checkpid 

	if [ $psid -ne 0 ]; then 
		echo "$APP_NAME is running! (pid=$psid)" 
	else 
		echo "$APP_NAME is not running" 
	fi 
} 


info() { 
	echo "System Information:" 
	echo "****************************" 
	echo `head -n 1 /etc/issue` 
	echo `uname -a` 
	echo 
	echo "JAVA_HOME=$JAVA_HOME" 
	echo `$JAVA_HOME/bin/java -version` 
	echo 
	echo "APP_HOME=$APP_HOME" 
	echo "APP_MAINCLASS=$APP_MAINCLASS" 
	echo "APP_NAME=$APP_NAME"
	echo "****************************" 
} 


case "$1" in 
	'start') 
		start 
		;; 
	'stop') 
		stop 
		;; 
	'restart') 
		stop 
		start 
		;; 
	'status') 
		status 
		;; 
	'info') 
		info 
		;; 
	*) 
		echo "Usage: $0 {start|stop|restart|status|info}" 
		exit 1 
esac 
exit 0

